POST http://localhost:8080/api/questions
Content-Type: application/json

{
  "text": "",
  "optionA": "France",
  "optionB": "Croatia",
  "optionC": "Brazil",
  "optionD": "Germany",
  "correctAnswerIndex": 1,
  "difficulty": "EASY",
  "categoryId": 2
}