POST http://localhost:8080/api/quiz/start?categoryId=1&difficulty=EASY
Content-Type: application/json

{
  "text": "Who won the 2018 World Cup?",
  "optionA": "France",
  "optionB": "Croatia",
  "optionC": "Brazil",
  "optionD": "Germany",
  "correctAnswerIndex": 0,
  "difficulty": "MEDIUM",
  "categoryId": 1
}